services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: success-academy-web
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/public/uploads  # ✅ this is good
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/success_academy
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: success-academy-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: success_academy
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

volumes:
  pgdata:
